version: '3.9'
services:
  mysql-usrm:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: spotify_secret_password
      MYSQL_DATABASE: spotify_reviewer
    networks:
      - micro-net
  mysql-usrc:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: comments_secret_password
      MYSQL_DATABASE: user_comments
      MYSQL_TCP_PORT: 3307
    networks:
      - micro-net
  usr-mgmt:
    image: usrm
    deploy:
      replicas: 3
    networks:
      - micro-net
    ports:
      - "4000:4000"
    depends_on:
      - mysql-usrm
  usr-comm:
    image: usrc
    deploy:
      replicas: 3
    networks:
      - micro-net
    ports:
      - "5000:5000"
    depends_on:
      - usr-mgmt
      - mysql-usrc
  spotify-connector:
    image: spotc
    deploy:
      replicas: 3
    networks:
      - micro-net
    ports:
      - "3000:3000"
    depends_on:
      - usr-mgmt
  web-application:
    image: weba
    deploy:
      replicas: 3
    networks:
      - micro-net
    ports:
      - "8080:8080"
    depends_on:
      - usr-mgmt
      - usr-comm
      - spotify-connector

networks:
  micro-net: